user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 26, in run_seekr_algorithm
    normalization_path = get_precomputed_normalization_path(parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 141, in get_precomputed_normalization_path
    raise SeekrServerError('Fasta file <' + fasta_file + '> not found for kmer_length=' +  str(parameters['kmer_length']) )
SeekrServerError.SeekrServerError: Fasta file <gencode.v27.lncRNA_transcripts.fa> not found for kmer_length=1
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 103, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 103, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 103, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 103, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 103, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 26, in run_seekr_algorithm
    normalization_path = get_precomputed_normalization_path(parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 141, in get_precomputed_normalization_path
    raise SeekrServerError('Fasta file <' + fasta_file + '> not found for kmer_length=' +  str(parameters['kmer_length']) )
SeekrServerError.SeekrServerError: Fasta file <gencode.v27.lncRNA_transcripts.fa> not found for kmer_length=7
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 131, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 62, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
user_set_files uploaded True
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/skr/seekrServer.py", line 133, in processUpload
    countsText, pearsons = run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/skr/seekrLauncher.py", line 105, in run_seekr_algorithm
    label=True, silent=True, binary=False, mean=mean, std=std)
  File "/Users/davidwc/workspace/skr/kmer_counts.py", line 93, in __init__
    self.seqs = self.reader.get_seqs()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 74, in get_seqs
    clean_data = self.get_lines()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 69, in get_lines
    self._read_data()
  File "/Users/davidwc/workspace/skr/fasta_reader.py", line 48, in _read_data
    raise IOError('Fasta file is empty')
OSError: Fasta file is empty
Running the algorithm took 1.273 seconds
Running the algorithm took 0.179 seconds
Running the algorithm took 0.042 seconds
Running the algorithm took 0.321 seconds
Zipping file of length 43591 took 0.059 seconds
Running the algorithm took 0.112 seconds
Zipping file of length 43591 took 0.010 seconds
Running the algorithm took 0.117 seconds
Zipping file of length 43591 took 0.008 seconds
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 215, in create_fasta
    return jsonify({'file-id': request})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Request 'http://localhost:8080/files/fasta' [POST]> is not JSON serializable
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 215, in create_fasta
    return jsonify({'file-id': request.data})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'' is not JSON serializable
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 214, in create_fasta
    application.logger.log(request.data)
TypeError: log() missing 1 required positional argument: 'msg'
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 216, in create_fasta
    return jsonify({'file-id': request.data})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'' is not JSON serializable
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/wrappers.py", line 885, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/test.py", line 884, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'ImmutableMultiDict' object is not callable
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Error, no file
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 224, in create_fasta
    session_helper.create_file(file, session, file_identifier, extension='fasta')
NameError: name 'file' is not defined
Error, no file
Error, no file
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error, no file
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 169, in process_jobs
    user_set_files = request.files['user_set_files']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
KeyError: 'user_set_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(json_parameters)
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(json_parameters)
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(json_parameters)
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(str(json_parameters))
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(str(json_parameters))
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(str(json_parameters))
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log(str(json_parameters))
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 172, in process_jobs
    application.logger.log('log')
TypeError: log() missing 1 required positional argument: 'msg'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 174, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
  File "/Users/davidwc/workspace/seekr/session_helper.py", line 45, in get_file
    file_path = _get_user_file_path(session, file_identifier, extension)
  File "/Users/davidwc/workspace/seekr/session_helper.py", line 32, in _get_user_file_path
    user_directory_name = session['directory_id']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'directory_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 199, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 199, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 199, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 199, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 199, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 199, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 201, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 201, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 202, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 202, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 233, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 202, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 236, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 176, in process_jobs
    user_set_files = session_helper.get_file(session, json_parameters['user_set_id'], extension='fasta')
  File "/Users/davidwc/workspace/seekr/session_helper.py", line 45, in get_file
    file_path = _get_user_file_path(session, file_identifier, extension)
  File "/Users/davidwc/workspace/seekr/session_helper.py", line 32, in _get_user_file_path
    user_directory_name = session['directory_id']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'directory_id'
Exception on /files/fasta [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 234, in create_fasta
    session_helper.create_file(file, session, file_identifier, extension='fasta')
  File "/Users/davidwc/workspace/seekr/session_helper.py", line 40, in create_file
    file_path = _get_user_file_path(session, file_identifier, extension)
  File "/Users/davidwc/workspace/seekr/session_helper.py", line 32, in _get_user_file_path
    user_directory_name = session['directory_id']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'directory_id'
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 202, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 237, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 202, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 237, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
Error in /jobs
Traceback (most recent call last):
  File "/Users/davidwc/workspace/seekr/seekrServer.py", line 202, in process_jobs
    counts, names, comparison_counts, comparison_names = _run_seekr_algorithm(parameters=parameters)
  File "/Users/davidwc/workspace/seekr/seekrLauncher.py", line 237, in _run_seekr_algorithm
    unnormalized_frequency_path, names_path = get_precomputed_frequency_path(comparison_set, parameters['kmer_length'])
TypeError: 'NoneType' object is not iterable
